Изменил Yaml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,11 +13,16 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Setup SSH key
+      - name: Setup SSH key + debug format
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
           chmod 600 ~/.ssh/deploy_key
+          ls -l ~/.ssh/deploy_key
+          head -n 3 ~/.ssh/deploy_key     # начало ключа
+          tail -n 3 ~/.ssh/deploy_key      # конец ключа — должен быть END + пустая строка
+          file ~/.ssh/deploy_key           # должно показать "PEM RSA private key" или "OpenSSH private key"
+          ssh-keygen -y -P "" -f ~/.ssh/deploy_key > /dev/null 2>&1 && echo "Key OK" || echo "Key INVALID"
           ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts || true
 
       - name: Deploy via SSH
